apiVersion: apps/v1
kind: Deployment
metadata:
  name: labdb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
     app: labdb
  template:
    metadata:
      name: labdb-pod
      labels:
        app: labdb
    spec:
      containers:
        - name: labapi
          image: potgamepong/labdb:latest
          volumeMounts:
            - name: labdb-storage
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
      volumes:
        - name: labdb-storage
          persistentVolumeClaim:
            claimName: nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: labdb-service
spec:
  type: ClusterIP
  selector:
    app: labdb
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: labapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
     app: labapi
  template:
    metadata:
      name: labapi-pod
      labels:
        app: labapi
    spec:
      containers:
        - name: labapi
          image: potgamepong/labapi:latest
          
---
apiVersion: v1
kind: Service
metadata:
  name: labapi-service
spec:
  type: NodePort
  selector:
    app: labapi
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: labapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
     app: labapp
  template:
    metadata:
      name: labapp-pod
      labels:
        app: labapp
    spec:
      containers:
        - name: labapp
          image: potgamepong/labapp:latest
---
apiVersion: v1
kind: Service
metadata:
  name: labapp-service
spec:
  type: NodePort
  selector:
    app: labapp
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30001